default_job = "run"

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.run]
command = ["./dev.sh"]
need_stdout = true
allow_warnings = true
background = true

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true
